# Generated by Django 5.0.3 on 2024-07-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elapp', '0002_alter_customer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
